//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_Ly_Tour_Du_Lich.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOKING
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BOOKING()
        {
            this.HOA_DON = new HashSet<HOA_DON>();
        }
    
        public int Ma_Booking { get; set; }
        public Nullable<int> NguoiLon { get; set; }
        public Nullable<int> TreEm { get; set; }
        public Nullable<int> EmBe { get; set; }
        public Nullable<int> Gia { get; set; }
        public Nullable<System.DateTime> NgayBooking { get; set; }
        public string PTTT { get; set; }
        public Nullable<System.DateTime> ThoiHan_TT { get; set; }
        public string LuuY { get; set; }
        public string XacnhanTT { get; set; }
        public string Ma_Tour { get; set; }
        public Nullable<int> Ma_KH { get; set; }
    
        public virtual KHACH_HANG KHACH_HANG { get; set; }
        public virtual TOUR TOUR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOA_DON> HOA_DON { get; set; }
    }
}
