//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_Ly_Tour_Du_Lich.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOUR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TOUR()
        {
            this.BOOKING = new HashSet<BOOKING>();
        }
    
        public string Ma_Tour { get; set; }
        public string Img { get; set; }
        public string Mota { get; set; }
        public string DiaDiem { get; set; }
        public string ThoiGian { get; set; }
        public Nullable<System.DateTime> NgayKhoiHanh { get; set; }
        public string GiaKM { get; set; }
        public string Gia { get; set; }
        public string DiaDiemKH { get; set; }
        public string LoaiHinh { get; set; }
        public string Ma_KM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOOKING> BOOKING { get; set; }
        public virtual KHUYEN_MAI KHUYEN_MAI { get; set; }
    }
}
